# futebol-api 

version: "3.6"

services:
  # Nginx Web Application
  webserver:
    container_name: futebol-api-webserver
    image: nginx:alpine
    working_dir: /var/www/futebol-api
    volumes:
      - .:/var/www/futebol-api
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=localhost

  # PHP-FPM
  php-fpm:
    container_name: futebol-api-php-fpm
    build: docker/php-fpm
    working_dir: /var/www/futebol-api
    volumes:
      - .:/var/www/futebol-api
      - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/8.2/fpm/conf.d/99-overrides.ini

  # MySQL
  mysql:
    container_name: futebol-api-mysql8
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=caching_sha2_password --character-set-server=latin1 --collation-server=latin1_swedish_ci
    environment:
      - MYSQL_ROOT_PASSWORD=futebol-api
      - MYSQL_DATABASE=futebol-api
      - MYSQL_USER=futebol-api
      - MYSQL_PASSWORD=futebol-api
    ports:
      - "3306:3306"
    volumes:
      - './docker/db/data:/var/lib/mysql'
      - './docker/db/my.cnf:/etc/mysql/conf.d/my.cnf'
      - './docker/db/sql:/docker-entrypoint-initdb.d'

  # MailHog
  mailhog:
    container_name: futebol-api-mailhog
    image: mailhog/mailhog:latest
    ports:
      - "8025:8025"

volumes:
  # minio-data
  futebol-api-minio-data:
    driver: local
